# Generated by Django 5.1.7 on 2025-03-14 04:26

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercareerexperience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usercareerexperience',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usercareerexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='usercareerexperience',
            index=models.Index(fields=['created_at'], name='users_userc_created_50b887_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerexperience',
            index=models.Index(fields=['updated_at'], name='users_userc_updated_9f505b_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerexperience',
            index=models.Index(fields=['deleted_at'], name='users_userc_deleted_2e0579_idx'),
        ),
        migrations.AddIndex(
            model_name='usereducation',
            index=models.Index(fields=['created_at'], name='users_usere_created_e123b0_idx'),
        ),
        migrations.AddIndex(
            model_name='usereducation',
            index=models.Index(fields=['updated_at'], name='users_usere_updated_ab28ef_idx'),
        ),
        migrations.AddIndex(
            model_name='usereducation',
            index=models.Index(fields=['deleted_at'], name='users_usere_deleted_5246e6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='users_userp_created_72cdd2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['updated_at'], name='users_userp_updated_6b3943_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['deleted_at'], name='users_userp_deleted_2b4d00_idx'),
        ),
        migrations.AddIndex(
            model_name='usersetting',
            index=models.Index(fields=['created_at'], name='users_users_created_c1803c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersetting',
            index=models.Index(fields=['updated_at'], name='users_users_updated_df4860_idx'),
        ),
        migrations.AddIndex(
            model_name='usersetting',
            index=models.Index(fields=['deleted_at'], name='users_users_deleted_3c17af_idx'),
        ),
    ]
