# Generated by Django 5.1.7 on 2025-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usercareerexperience_users_userc_created_50b887_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercareerexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
