# Generated by Django 5.1.7 on 2025-03-14 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("requirements", models.JSONField(default=list)),
                ("salary_range", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("full_time", "정규직"),
                            ("part_time", "파트타임"),
                            ("contract", "계약직"),
                            ("internship", "인턴십"),
                            ("temporary", "일용직"),
                            ("remote", "재택근무"),
                            ("freelance", "프리랜서"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("internet", "인터넷"),
                            ("fintech", "핀테크"),
                            ("education", "교육"),
                            ("healthcare", "의료"),
                            ("e_commerce", "전자 상거래"),
                            ("real_estate", "부동산"),
                            ("logistics", "물류"),
                            ("marketplace", "마켓플레이스"),
                            ("social_network", "소셜 네트워크"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("is_hiring", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category"], name="jobs_job_categor_653d6e_idx"
                    ),
                    models.Index(
                        fields=["industry"], name="jobs_job_industr_a3aeef_idx"
                    ),
                    models.Index(
                        fields=["posted_at"], name="jobs_job_posted__7edcdf_idx"
                    ),
                    models.Index(
                        fields=["is_hiring"], name="jobs_job_is_hiri_8bd55b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("resume_uri", models.URLField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["applied_at"], name="jobs_jobapp_applied_23c887_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("bookmarked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "bookmarked_at"],
                        name="jobs_jobboo_user_id_833883_idx",
                    )
                ],
                "unique_together": {("user", "job")},
            },
        ),
    ]
