# Generated by Django 5.1.7 on 2025-03-19 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_created_at_alter_job_posted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expired_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="jobbookmark",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobbookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["expired_at"], name="job_expired_22eae9_idx"),
        ),
    ]
