# Generated by Django 5.1.7 on 2025-04-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_created_by_job_job_created_321fb5_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("requirements", models.JSONField(default=list)),
                ("salary_range", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("full_time", "정규직"),
                            ("part_time", "파트타임"),
                            ("contract", "계약직"),
                            ("internship", "인턴십"),
                            ("temporary", "일용직"),
                            ("remote", "재택근무"),
                            ("freelance", "프리랜서"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("internet", "인터넷"),
                            ("fintech", "핀테크"),
                            ("education", "교육"),
                            ("healthcare", "의료"),
                            ("e_commerce", "전자 상거래"),
                            ("real_estate", "부동산"),
                            ("logistics", "물류"),
                            ("marketplace", "마켓플레이스"),
                            ("social_network", "소셜 네트워크"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("review_comment", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(null=True)),
                (
                    "created_job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posting_request",
                        to="jobs.job",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posting_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_job_posting_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_posting_request",
                "indexes": [
                    models.Index(
                        fields=["status"], name="job_posting_status_5f2270_idx"
                    ),
                    models.Index(
                        fields=["requested_by"], name="job_posting_request_8225c3_idx"
                    ),
                    models.Index(
                        fields=["reviewed_by"], name="job_posting_reviewe_e75a05_idx"
                    ),
                ],
            },
        ),
    ]
