# Generated by Django 5.1.7 on 2025-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("search_word", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("visa", "비자 정보"),
                            ("culture", "문화 정보"),
                            ("industry", "산업 정보"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("source_url", models.URLField()),
            ],
            options={
                "db_table": "insights",
                "indexes": [
                    models.Index(fields=["category"], name="insights_category_idx"),
                    models.Index(
                        fields=["search_word"], name="insights_search_word_idx"
                    ),
                ],
            },
        ),
    ]
