# Generated by Django 5.1.7 on 2025-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="source_url",
            field=models.TextField(),
        ),
    ]
