# Generated by Django 5.1.7 on 2025-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0002_alter_insight_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("keyword", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_searched_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "search_keywords",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="search_keywords_is_active_idx"
                    )
                ],
            },
        ),
    ]
