# Generated by Django 5.1.7 on 2025-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0003_searchkeyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="source_url",
            field=models.CharField(max_length=512),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(fields=["source_url"], name="insights_source_url_idx"),
        ),
    ]
