# Generated by Django 5.1.7 on 2025-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0004_alter_insight_source_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="source_url",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
