# Generated by Django 5.1.7 on 2025-04-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0005_alter_insight_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("visa_type", models.CharField(max_length=50)),
                ("requirements", models.JSONField()),
                ("process", models.JSONField()),
                ("duration", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "visa_info",
                "indexes": [models.Index(fields=["visa_type"], name="visa_type_idx")],
            },
        ),
    ]
