# Generated by Django 5.1.7 on 2025-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0006_visainfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainfo",
            name="visa_type",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
