# Generated by Django 5.1.7 on 2025-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0007_alter_visainfo_visa_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "culture_type",
                    models.CharField(
                        choices=[
                            ("business", "비즈니스 문화"),
                            ("daily", "일상생활"),
                            ("social", "사회적 관습"),
                            ("food", "음식 문화"),
                            ("housing", "주거 문화"),
                            ("transportation", "교통"),
                            ("entertainment", "여가 생활"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("tags", models.JSONField()),
                ("source_urls", models.JSONField(default=list)),
            ],
            options={
                "db_table": "culture_info",
                "indexes": [
                    models.Index(fields=["culture_type"], name="culture_type_idx")
                ],
            },
        ),
    ]
