# Generated by Django 5.1.7 on 2025-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0008_cultureinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureinfo",
            name="culture_type",
            field=models.CharField(
                choices=[
                    ("business", "비즈니스 문화"),
                    ("daily", "일상생활"),
                    ("social", "사회적 관습"),
                    ("food", "음식 문화"),
                    ("housing", "주거 문화"),
                    ("transportation", "교통"),
                    ("entertainment", "여가 생활"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="IndustryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("industry_type", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("trends", models.JSONField()),
                ("opportunities", models.JSONField()),
            ],
            options={
                "db_table": "industry_info",
                "indexes": [
                    models.Index(fields=["industry_type"], name="industry_type_idx")
                ],
            },
        ),
    ]
