# Generated by Django 5.1.7 on 2025-04-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0010_alter_visainfo_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultureinfo",
            name="culture_type",
            field=models.CharField(
                choices=[
                    ("business", "비즈니스 문화"),
                    ("daily", "일상생활"),
                    ("social", "사회적 관습"),
                    ("food", "음식 문화"),
                    ("housing", "주거 문화"),
                    ("transportation", "교통"),
                    ("entertainment", "여가 생활"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="industryinfo",
            name="industry_type",
            field=models.CharField(max_length=50),
        ),
    ]
