# Generated by Django 5.1.7 on 2025-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0004_alter_authuser_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="authuser",
            index=models.Index(
                fields=["social_id", "social_provider"], name="user_social__d04ba0_idx"
            ),
        ),
    ]
